"""50 common Irish words with English translations and emoji."""

WORDS = [
    {"english": "Cat", "irish": "Cat", "emoji": "\U0001f431"},
    {"english": "Dog", "irish": "Madra", "emoji": "\U0001f415"},
    {"english": "House", "irish": "Teach", "emoji": "\U0001f3e0"},
    {"english": "Tree", "irish": "Crann", "emoji": "\U0001f333"},
    {"english": "Water", "irish": "Uisce", "emoji": "\U0001f4a7"},
    {"english": "Book", "irish": "Leabhar", "emoji": "\U0001f4d6"},
    {"english": "Sun", "irish": "Grian", "emoji": "\u2600\ufe0f"},
    {"english": "Moon", "irish": "Gealach", "emoji": "\U0001f319"},
    {"english": "Star", "irish": "R\u00e9alta", "emoji": "\u2b50"},
    {"english": "Fish", "irish": "Iasc", "emoji": "\U0001f41f"},
    {"english": "Bird", "irish": "\u00c9an", "emoji": "\U0001f426"},
    {"english": "Flower", "irish": "Bl\u00e1th", "emoji": "\U0001f338"},
    {"english": "Car", "irish": "Carr", "emoji": "\U0001f697"},
    {"english": "Door", "irish": "Doras", "emoji": "\U0001f6aa"},
    {"english": "Window", "irish": "Fuinneog", "emoji": "\U0001fa9f"},
    {"english": "Table", "irish": "Bord", "emoji": "\U0001f37d\ufe0f"},
    {"english": "Chair", "irish": "Cathaoir", "emoji": "\U0001fa91"},
    {"english": "Bread", "irish": "Ar\u00e1n", "emoji": "\U0001f35e"},
    {"english": "Milk", "irish": "Bainne", "emoji": "\U0001f95b"},
    {"english": "Apple", "irish": "\u00dall", "emoji": "\U0001f34e"},
    {"english": "Eye", "irish": "S\u00fail", "emoji": "\U0001f441\ufe0f"},
    {"english": "Hand", "irish": "L\u00e1mh", "emoji": "\u270b"},
    {"english": "Head", "irish": "Ceann", "emoji": "\U0001f9d1"},
    {"english": "Foot", "irish": "Cos", "emoji": "\U0001f9b6"},
    {"english": "Heart", "irish": "Cro\u00ed", "emoji": "\u2764\ufe0f"},
    {"english": "King", "irish": "R\u00ed", "emoji": "\U0001f451"},
    {"english": "Queen", "irish": "Banr\u00edon", "emoji": "\U0001f478"},
    {"english": "Boy", "irish": "Buachaill", "emoji": "\U0001f466"},
    {"english": "Girl", "irish": "Cail\u00edn", "emoji": "\U0001f467"},
    {"english": "Man", "irish": "Fear", "emoji": "\U0001f468"},
    {"english": "Woman", "irish": "Bean", "emoji": "\U0001f469"},
    {"english": "Child", "irish": "P\u00e1iste", "emoji": "\U0001f476"},
    {"english": "School", "irish": "Scoil", "emoji": "\U0001f3eb"},
    {"english": "Teacher", "irish": "M\u00fainteoir", "emoji": "\U0001f469\u200d\U0001f3eb"},
    {"english": "Friend", "irish": "Cara", "emoji": "\U0001f91d"},
    {"english": "Food", "irish": "Bia", "emoji": "\U0001f372"},
    {"english": "Rain", "irish": "B\u00e1isteach", "emoji": "\U0001f327\ufe0f"},
    {"english": "Wind", "irish": "Gaoth", "emoji": "\U0001f4a8"},
    {"english": "Fire", "irish": "Tine", "emoji": "\U0001f525"},
    {"english": "Earth", "irish": "Talamh", "emoji": "\U0001f30d"},
    {"english": "Mountain", "irish": "Sliabh", "emoji": "\U0001f3d4\ufe0f"},
    {"english": "River", "irish": "Abhainn", "emoji": "\U0001f3de\ufe0f"},
    {"english": "Sea", "irish": "Farraige", "emoji": "\U0001f30a"},
    {"english": "Road", "irish": "B\u00f3thar", "emoji": "\U0001f6e4\ufe0f"},
    {"english": "Shoe", "irish": "Br\u00f3g", "emoji": "\U0001f45f"},
    {"english": "Coat", "irish": "C\u00f3ta", "emoji": "\U0001f9e5"},
    {"english": "Hat", "irish": "Hata", "emoji": "\U0001f3a9"},
    {"english": "Pen", "irish": "Peann", "emoji": "\U0001f58a\ufe0f"},
    {"english": "Ball", "irish": "Liathróid", "emoji": "\u26bd"},
    {"english": "Egg", "irish": "Ubh", "emoji": "\U0001f95a"},
]

# English -> Irish lookup for communicate-mode translation
EN_TO_IRISH = {w["english"].lower(): w["irish"] for w in WORDS}
